# curl -L
#  -H "Accept: application/vnd.github+json"
#  -H "Authorization: Bearer <Y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>"
#  -H "X-GitHub-Api-Version: 2022-11-28"
#  https://api.github.com/notifications
GET https://api.github.com/repos/Overflow922/notification-bot/issues/comments/1962915997
Accept: application/vnd.github+json
Authorization: Bearer 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
X-Github-Api-Version: 2022-11-28
all: true

# curl -L
#  -H "Accept: application/vnd.github+json"
#  -H "Authorization: Bearer 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"
#  -H "X-GitHub-Api-Version: 2022-11-28"
#  https://api.github.com/repos/OWNER/REPO/comments/COMMENT_ID
###
GET https://api.github.com/repos/Overflow922/notification-bot/pulls/13
Accept: application/vnd.github+json
Authorization: Bearer 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
X-GitHub-Api-Version: 2022-11-28

###

GET https://api.github.com/repos/Galaxy13/TestCherryPickRepository/pulls/1/commits
Accept: application/vnd.github+json
Authorization: Bearer
X-GitHub-Api-Version: 2022-11-28



###

