github:
    base_url_git: 'github.com'
    base_url_api: 'https://api.github.com'
    headers:
        Accept: 'application/vnd.github+json'
        Authorization: 'Bearer '
        X-Github-Api-Version: '2022-11-28'
    notification:
        notification_url: 'notification'
        json_request: 'url'
        json_comment: 'latest_comment_url'
    bot:
      username: 'Galaxy13'
      token: ''

