github:
    base_url_git: 'github.com'
    base_url_api: 'https://api.github.com'
    headers:
        Accept: 'application/vnd.github+json'
        Authorization: 'Bearer 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'
        X-Github-Api-Version: '2022-11-28'
    notification:
        notification_url: 'notification'
        json_request: 'url'
        json_comment: 'latest_comment_url'
    bot:
        username: 'Retroider'
        token: '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'

