github:
    base_url: 'https://api.github.com'
    headers:
        Accept: 'application/vnd.github+json'
        Authorization: 'Bearer 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'
        X-Github-Api-Version: '2022-11-28'
    notification:
        notification_url: 'notification'
        json_request: 'url'
        json_comment: 'latest_comment_url'

